### PR TITLE
License project under AGPLv3+

### PR DESCRIPTION
**Pull request by kabalin**
Following the discussion at #448 it has been agreed to use GNU AGPLv3+ for the PastVu app code.

I suggest to use simplified copyright and license declaration in the files. 
```
/**
 * Copyright: Contributors to the PastVu project.
 * GNU Affero General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/agpl.txt)
 */
```

Not having full GPL prefix in files does not violate license, as it permits to do so:
> ... and each file should have at least the "copyright" line and a pointer to where the full notice is found.

With regard to copyright, suggested form is recommended by Linux Foundation: https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects

There are projects that use similar approach for files licensing, [Ansible for example](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#copyright-and-license).

For now adding notice to eslint covered files only, some files are probably omited, but this will be adressed alongside upcoming changes on client side.

Please also approve changes in documentation: https://github.com/PastVu/docs/pull/7

### CODE REVIEW

**Comment by kabalin** [comment]
@klimashkin just thinking, we can actually use different header for all existing files to acknowledge your work: 
```
/**
 * Copyright: (c) 2012-2020, Paul Klimashkin
 * GNU Affero General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/agpl.txt)
 */
```
And all new files created from now on will use the new header per suggestion.

**Review by klimashkin — APPROVED** [review]

**Comment by klimashkin** [comment]
I'm good with all files copyrighted to pastvu

**Comment by kabalin** [comment]
> I'm good with all files copyrighted to pastvu

Do you mean the copyright before 2020 goes to PastVu project, but after - to contributors? e.g. for existing files:
```js
/**
 * Copyright: (c) 2009-2020, PastVu project
 * GNU Affero General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/agpl.txt)
 */
 ```
 
 new files (created after 2020):
```js
/**
 * Copyright: Contributors to the PastVu project
 * GNU Affero General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/agpl.txt)
 */
 ```

Or keeping this PR as is (latter header for all files)?

**Comment by kabalin** [comment]
Also pinging @anvaruk and @paul-k-pastvu for opinion or thumb-up, so we all are agreed.

**Comment by kabalin** [comment]
I assume everyone is agree with the current copyright statment. I just made a small change to make it shorter and updated PR:

```
/**
 * Copyright: The PastVu contributors.
 * GNU Affero General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/agpl.txt)
 */
```

**Pull request merged**
