### PR TITLE
MongoDB 4.x migration - Part 1

### PR DESCRIPTION
**Pull request by kabalin**
### What is included
This patch-set includes a first part of changes required for migration to MongoDB 4:

* Updating Mongoose 4.9.9 -> 5.10.15  cf64677
* Docker-compose and Readme update to use MongoDB 4.4 8970f26

* Mongodb connection instance changes for Mongoose 5.x  29e0fa9

  This includes adding new connection that adjust Mongoose behaviour to latest MongoDB API driver requirement:
  * `useUnifiedTopology: true` Use new topology engine (since MongoDB API driver 3.3) [more...](https://mongoosejs.com/docs/deprecations.html#useUnifiedTopology)
  * `useNewUrlParser: true` Use new connection string parser [more...](https://mongoosejs.com/docs/deprecations.html#useNewUrlParser)
  * `useCreateIndex: true` Use createIndex internally (`ensureIndex` is deprecated in MongoDB API driver 3.2) [more...](https://mongoosejs.com/docs/deprecations.html#useCreateIndex)
  * `useFindAndModify: false` Use findOneAndUpdate interally (`findAndModify` is deprecated in MongoDB API driver 3.1) [more...](https://mongoosejs.com/docs/deprecations.html#useFindAndModify)

  Also this includes options declaration changes [more...](https://mongoosejs.com/docs/connections.html#v5-changes)

* Replace deprecated `count()` with alternatives. 383226a
  As of MongoDB driver 3.1 `count()` is [deprecated](https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#count)
  Using `countDocuments()` or fast alternative `estimatedDocumentCount()` where applicable [more...](https://mongoosejs.com/docs/deprecations.html#count)

* Replace deprecated `remove()` with alternatives d1e2403
  As of MongoDB driver 3.1 `remove()` is [deprecated](https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#remove)
  Using `deleteOne` and `deleteMany` depending on context [more...](https://mongoosejs.com/docs/deprecations.html#remove)
  Also addressed API change in returned object format when applied to query. 

* Replace deprecated `update()` with alternatives a34f81f
  As of MongoDB driver 3.1 `update()` is [deprecated](https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#update)
  Using `updateOne` and `updateMany` depending on context [more...](https://mongoosejs.com/docs/deprecations.html#update)

* Replace deprecated `insert()` with alternatives 5c9ad53
  As of MongoDB driver 3.1 `insert()` is [deprecated](https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#insert)
  Using `insertOne` and `insertMany` depending on context.

* Code is also checked for presence of other operators not compatible with current version.

Additional sources used for this work:
https://github.com/Automattic/mongoose/blob/master/History.md#500-rc0--2017-12-28
https://mongoosejs.com/docs/migrating_to_5.html

At this point, app is working with no errors or deprecation warnings (apart of those listed in TODO below). I tested a number of different use cases that came to my mind (all common user actions with photos, profile, comments, conversion, clusters generations), though it still needs thorough testing on staging (or on dedicated instance for this change).

There are some todo tasks are left (if this one is merged, they will come as separate PRs, otherwise patches will be added to this branch).

### TODO

1. We are using `db.eval()` here:
https://github.com/PastVu/pastvu/blob/master/controllers/connection.js#L98
This [has been deprecated](https://mongodb.github.io/node-mongodb-native/3.1/api/Db.html#eval) with no replacement alternative, so parts where we use it needs to be re-written. For more info why it has been removed, see https://jira.mongodb.org/browse/SERVER-17453 

2. On staring the app I am getting `DeprecationWarning: collection.save is deprecated.` message coming from MongoDB driver API, it is caused by this line:
https://github.com/PastVu/pastvu/blob/master/controllers/systemjs.js#L27
If I am replacing that with `insertOne` ([per API docs](https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#save)), I start getting same deprecation warnings coming from `basepatch/v1.3.0.7.js` that got similar use of `collection.save()`. I am not sure if that is correct, may be @klimashkin can explain why it is pulling patches (or is it supposed to, in that case patches need code changes too)?

3. As discussed https://github.com/PastVu/pastvu/issues/191#issuecomment-729706528, it might be a good idea to convert indexes from [`2d`](https://docs.mongodb.com/manual/core/2d/) to [`2dsphere`](https://docs.mongodb.com/manual/core/2dsphere/), so we can use [geospacial queries](https://docs.mongodb.com/manual/geospatial-queries/#id1) in full where required.

### CODE REVIEW

**Comment by kabalin** [comment]
**About TODO 2** (see https://github.com/PastVu/pastvu/pull/307#issue-526111094):

I had a quick look today how patches are added and also in a change history. In some cases there is a commit that commenting patch include line out and sometimes not. I assume patches are idempotent since you leave ones included permanently like at https://github.com/PastVu/pastvu/blob/master/app.js#L27 Given this, two things to outline:
1. So, patches do not require code changes, I found the answer to my question, we just write next one according to new API requirements and can safely remove include requirement for `v1.3.0.7.js`.
2. I did not find in the git history if [`basepatch/v1.3.0.8.js`](https://github.com/PastVu/pastvu/blob/master/basepatch/v1.3.0.8.js) was ever applied? If not - do we still need to apply it (in that case in next upgrade we can rename file to match version and add more stuff)?

**Comment by aeifn** [comment]
> I had a quick look today how patches are added and also in a change history. In some cases there is a commit that commenting out patch `include..` line in `app.js`, but not in all cases. I assume patches are idempotent since you leave ones included permanently like at https://github.com/PastVu/pastvu/blob/master/app.js#L27 Given this, two things to outline:

I think we need something like `manage.py` in django.
For example, to apply new migrations, we will run: `./bin/manage.js migrate`

**Comment by kabalin** [comment]
> I think we need something like `manage.py` in django.
> For example, to apply new migrations, we will run: `./bin/manage.js migrate`

How that is done at the moment, I can't find where DB stored function `pastvuPatch` is executed?

**Comment by aeifn** [comment]
> > I think we need something like `manage.py` in django.
> > For example, to apply new migrations, we will run: `./bin/manage.js migrate`
> 
> How that is done at the moment, I can't find where DB stored function `pastvuPatch` is executed?

It seems like it runs manually in the mongo shell, after `pastvuPatch` is stored.

**Comment by kabalin** [comment]
I spent some time yesterday looking at TODO 1 and TODO 2 (per https://github.com/PastVu/pastvu/pull/307#issue-526111094). Those two need to be approached together. 

So, [`controllers/systemjs.js`](https://github.com/PastVu/pastvu/blob/master/controllers/systemjs.js) is used to populate stored functions to the DB:
```
{ "_id" : "archiveExpiredSessions" }
{ "_id" : "clusterPhotosAll" }
{ "_id" : "photosToMapAll" }
{ "_id" : "convertPhotosAll" }
{ "_id" : "calcUserPhotoCommentsRegionsStat" }
{ "_id" : "regionsAssignPhotos" }
{ "_id" : "regionsAssignPhotosOld" }
{ "_id" : "regionsAssignComments" }
{ "_id" : "regionsCalcBBOX" }
{ "_id" : "regionsCalcPointsNum" }
{ "_id" : "regionsCalcPolygonsNum" }
{ "_id" : "regionClearPhotoTitle" }
{ "_id" : "regionsAllClearPhotoTitle" }
{ "_id" : "calcUserStats" }
{ "_id" : "calcUsersObjectsRelStats" }
{ "_id" : "calcPhotoStats" }
{ "_id" : "regionsCalcCenter" }
{ "_id" : "calcRegionStats" }
{ "_id" : "pruneHistAgents" }
{ "_id" : "pruneLocalHistIPs" }
{ "_id" : "toPrecision" }
{ "_id" : "toPrecision6" }
{ "_id" : "geoToPrecision" }
{ "_id" : "toPrecisionRound" }
{ "_id" : "geoToPrecisionRound" }
{ "_id" : "spinLng" }
{ "_id" : "getDistanceFromLatLonInKm" }
{ "_id" : "linkifyUrlString" }
{ "_id" : "inputIncomingParse" }
{ "_id" : "pastvuPatch" }
```

Those functions are then called using [`dbEval`](https://github.com/PastVu/pastvu/blob/master/controllers/connection.js#L98) like in example [here](https://github.com/PastVu/pastvu/blob/master/controllers/region.js#L503), some of those functions are calling other stored functions, and some have no reference in a code any more (thus can be removed). Calling them using `db.eval()` is [no longer possible](https://docs.mongodb.com/manual/release-notes/4.2/#removed-commands-and-methods) since Mongo 4.2. 

I first thought as quick fix I might actually refactor body of `dbEval` function to query `system.js` collection using `findOne` and retrieve requested stored function, deserialize it using `bson` lib (we already have in packages), convert it into [`Function`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) and call, the but then I found that some functions are using other stored functions, so I gave up this idea. I think it is better not to store them and either move to dedicated modules where they should belong and call normal way, or make a "helper" module that will keep them in one file as now and export only those needed to be used in other places. Would be good to hear opinion of @klimashkin regarding this and also would be good to know a rationale why they were designed as stored functions at first place, may be I am missing something important here.

The exception is stored function `pastvuPatch` which we have no means to execute after upgrade, so we need an alternative way to manage DB upgrades. I like the idea of @aeifn to have a separate endpoint, e.g. `npm migrate`, we may store current app version in `settings` collection in DB and use it as a reference to find out which patches needs to be applied (by comparing it with version in `package.json`). But before implementing that, would be good to check if there is standard node.js package for upgrade management that can be used, it may save some time.

Other than that, if this PR can be merged to `mongo4` feature branch, that would be nice, I'd rather avoid making it more complicated by adding systemjs refactoring, would rather send a separate PR after this one.

**Comment by klimashkin** [comment]
@kabalin Yes, finally. System.js was the reason why we could not update to Mongo 4.
It contains a bunch of helper/cleaning procedures, that we call from time to time. It was written there for all the heavy lifting operations, which would be extremely costly to call from the application, like iterations and updates over whole collections, etc, because that would mean copying a big chunk of the database in interservice calls, which would be bad for procedure performance and for the nodejs processes. So those functions are supposed to be called once from the nodejs application and just get the acknowledgment on the result (success/error). And when Mongo deprecated such calls since version 3, it was not clear how to change that. There were many discussions out there on different forums, maybe now there is an official approach to do that.

> and some have no reference in a code any more

Many of those were written specifically to be called from the mongo console, they don't have references in the application, but it doesn't mean they are dead (even though some stocktaking is needed)

**Comment by mkgrgis** [comment]
> It contains a bunch of helper/sanitizing/cleaning procedures, that we call from time to time. It was written there for all the heavy lifting operations, which would be extremely costly to call from the application, like iterations and updates over whole collections <...>

@klimashkin , when I considered a possible decomposition of a data model in a [semi-regular PostgreSQL JSON style](https://postgrespro.ru/docs/postgresql/13/functions-json), these functions caused the most difficulty. Some of them will decompose well into table relationships. All of these functions are equivalent of database procedures with good performance. Therefore, in simple sketches, it was not possible to achieve the performance metrics of [this outdated example](https://habr.com/ru/company/itsumma/blog/436416/) with a simple transfer of logic. But now in PostgreSQL, anybody can freely combine regular and JSON structures to optimize performance. Note that SQL `INSERT` will not be intensive with except for comments. For the images geo objects there is [PostGIS](https://postgis.net/) for intersecting and regions management. Would you be interested in sketching for the main MongoDB branches in PostgreSQL JSON style after moving functions outside of `db.eval`?

**Comment by kabalin** [comment]
> It contains a bunch of helper/sanitizing/cleaning procedures, that we call from time to time. It was written there for all the heavy lifting operations, which would be extremely costly to call from the application, like iterations and updates over whole collections, etc, because that would mean copying a big chunk of the database in interservice calls, which would be bad for procedure performance and for the nodejs processes. 

Thanks @klimashkin for providing some insight on this, makes more sense now. [Mongo 4.2 blog post gives](https://www.mongodb.com/blog/post/going-in-mongodb-42) a good summary of deprecation reason and implies how this has to be handled instead:

> The eval command went because it no longer made sense to take a global lock on the server when running a script, blocking all operations on the database. Many uses of eval used that global lock to ensure consistency on the database as it ran cross collection transactions. Since 4.0, it's been more sensible and effective to use MongoDB's transaction support to get those guarantees without effectively shutting down the server, which is what eval did.

So, to achieve data integrity within procedure run, we can use transactions where needed. To address performance issues, we can off-load processing for those functions into separate node process. I suggest to implement job queue for our tasks processing based on [Bull](https://www.npmjs.com/package/bull). It is using Redis for queue management and [fairly strightforward](https://www.npmjs.com/package/bull#quick-guide) to use. Heavier tasks can be run using [separate queue processes](https://www.npmjs.com/package/bull#separate-processes). It possible to schedule recurring jobs, control concurrency and retrieve run history (which might be handy if we want to show some info on completed jobs in admin interface). It also features [cluster support](https://www.npmjs.com/package/bull#cluster-support), that allows to scale the number of runners if required. Here is its [API reference](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md). 

I also considered alternatives such as [bee-queue](https://github.com/bee-queue/bee-queue), essentially they all do the same thing, but have different features. `bee-queue` for example seems lighter implementation, does not support recurrence, which I think we can benefit from (there is a number of recurring tasks already in the code that can be converted to jobs), and does not seem scalable. `bull` looks like a better option given number of features and popularity, but we can discuss alternatives should anyone propose one or have a strong opinion against 'bull'.

I suggest to proceed as follows:

**For the purpose of Mongo 4 migration (#191):**
* Create a separate tasks runner service. Refactor `systemjs` function into queues processing functions. All `dbEval` calls throughout the code needs to be replaced with `someQueueName.add(...)` (where `dbEval` expects result, it will be returned via promise). All output and progress reporting will go to standard log for now.
* Someone (not pointing to @klimashkin 😉) needs to review existing `systemjs` tasks and say which are not required (any comments on those we keep is a plus, e.g. when each one should be used).
* Add a simple UI in admin to trigger those tasks that used to run via mongo console.

When above items are completed, we will be able to proceed to final task - refactor how to apply patches. I suggest to use [node-migrate](https://github.com/tj/node-migrate) or similar framework, we will get to this in details later.

**Follow up tasks (these can be done after migration and will need to be recorded in separate tickets)**
* Review and refactor existing regular tasks to recurring jobs, good starting candidates are Sitemap service and `regionStatQueueDrain`.
* Moving notifications sending (`notifierConveyor`) to recurring job (this will address #296).
* Review performance, allow concurrency for less resource-intensive tasks, ensure heavy tasks are run as separate processes and not blocking queue.

**Pull request merged**
