### PR TITLE
MongoDB 4.x migration - Part 3

### PR DESCRIPTION
**Pull request by kabalin**
This is part 3 of Mongo 4 migration task (#191). The patchset addressing the points outlined in https://github.com/PastVu/pastvu/pull/307#issuecomment-736070684 that were required to proceed with preparing for  migration:

* Implementing [Bull](https://github.com/OptimalBits/bull/) queues for jobs processing in a separate node instance.
* Migrating DB stored functions that were called using `dbEval` ([deprecated in Mongo 4.2](https://docs.mongodb.com/manual/release-notes/4.2/#removed-commands-and-methods)) into controllers, so they can be used by respective queue processors.

The queue management is in a bit experimental state now (I never used Bull before). You can see from patches history that it evolved already from my initial approach I started with, and there is definitely room for improving it further. So, please ask any questions or share your suggestions.

### What is included

**1. Worker instance**

Worker is designed to be run as a separate node process (`npm run worker`), it has been added to docker compose file for convenience of developer. The role of worker is:
* Register queue processors for regular tasks
* Schedule regular tasks
* Register processors for user jobs - those tasks that are normally triggered by the app, but needs to be run at the backend.

**2. Queue controller**  

Queue controller [`controllers/queue.js`](https://github.com/kabalin/pastvu/blob/mongo4-p3/controllers/queue.js) helps to manage the queue:

* `createQueue` method to initialise the queue, implement progress and error logging (see [`worker.js`](https://github.com/kabalin/pastvu/blob/mongo4-p3/worker.js) for use example).
* Implements graceful shutdown of queues.
* `JobCompletionListener` class designed to register a callback on any job completion. This is mainly useful for the app instance to do something on regular task completion (real example - calling `session.regetUsersAfterStatsUpdate` on front-ends each time `calcUserStats` finishes at back-end worker).
* `runJob` method to trigger job with given params and get result object back. This is mainly useful for the app instance to trigger job on the worker ang get result back.

**3. Migrated methods**

All methods that previously were called via `dbEval` are migrated to controllers:

Regular tasks:
* `session.archiveExpiredSessions` (with `session.cleanArchivedSessions` front-end callback on completion).
* `session.calcUserStats` (with `session.regetUsersAfterStatsUpdate` front-end callback on completion).

User jobs:
* `converter.convertPhotosAll` c995a40
* `cluster.clusterPhotosAll` 96eb5dd
* `region.calcRegionStats` 8d8b752

Other:
* `dbEval` function is removed, migrated methods have been removed from `systemjs` controller.

### About other `system.js` methods

DB stored functions that have not been called using `dbEval` are remaining in `systemjs` controller. It is still possible to call them using Mongo console by executing `db.loadServerScripts()` and making required function call.  Those remaining methods are:
```
{ "_id" : "photosToMapAll" }
{ "_id" : "calcUserPhotoCommentsRegionsStat" }
{ "_id" : "regionsAssignPhotos" }
{ "_id" : "regionsAssignPhotosOld" }
{ "_id" : "regionsAssignComments" }
{ "_id" : "regionsCalcCenter" }
{ "_id" : "regionsCalcPointsNum" }
{ "_id" : "regionsCalcBBOX" }
{ "_id" : "regionsAllClearPhotoTitle" }
{ "_id" : "regionClearPhotoTitle" }
{ "_id" : "calcUsersObjectsRelStats" }
{ "_id" : "calcPhotoStats" }
{ "_id" : "regionsCalcPolygonsNum" }
{ "_id" : "pruneLocalHistIPs" }
{ "_id" : "pruneHistAgents" }
{ "_id" : "toPrecision" }
{ "_id" : "toPrecision6" }
{ "_id" : "toPrecisionRound" }
{ "_id" : "geoToPrecision" }
{ "_id" : "geoToPrecisionRound" }
{ "_id" : "spinLng" }
{ "_id" : "getDistanceFromLatLonInKm" }
{ "_id" : "linkifyUrlString" }
{ "_id" : "inputIncomingParse" }
```
While some of them are clearly helpers (e.g. `toPrecision`, `spinLng`, etc.), I am not sure about others. I see some of them were used in patches. Would be good if @klimashkin reviewed them, so we decide which ones we need to keep (and if it worth adding possibility to trigger any of them from UI), perhaps we can have a separate ticket with revision details, so we keep it recorded separately? In either case, this is not a blocker for Mongo 4 migration any more.

### What is left to do

Next and final task is that was planned is to refactor how we apply DB patches. Given it is still possible to run DB stored functions using command line, we can carry on using old method in theory (by including basepatch that creates stored function which is then being run manually via mongo CLI). Although, I suggest to address this task given we make a number of significant changes anyway, so we have DB migration implemented predictable and organised way.

### CODE REVIEW

**Comment by kabalin** [comment]
### Usage

User task:
```
// In the controller define a function that need to be triggered by job:
export const myTask = async function (param) {
    // do something...
    console.log(param); // {a: 1}
    return Promise.resolve({
        data: {b: 2},
        message: "My Task is completed", // optional argument, will be shown in logger output.
    });
}
```
```
// In worker add new processor named "myTask" to existing setupUserJobsQueue function:
function setupUserJobsQueue() {
    createQueue('userjobs').then(userJobsQueue => {
        // Some other processors definitions are already listed here.

        // when job 'myTask' is called, run myTask function in the controller.
        userJobsQueue.process('myTask', job => myTask(job.data));
    });
}
```
```
// In any other place where you need to run job in worker process:
const result = await runJob('myTask', {a: 1});

if (result && result.error) {
    // Any exceptions in myTask or Promise.reject() there will land here.
    console.log(result.error.message);
}
console.log(result); // {b: 2} - this is what myTask returned in data argument
```

Regular job:
```
// In the controller define a function that need to be triggered by regular job:
export const myRegularTask = async function () {
    // do something...
    return Promise.resolve({
        data: {c: 3},
        message: "My Task is completed", // optional argument, will be shown in logger output.
    });
}
```

_So far all regular jobs were session related, thus queue is called "session". Initially I planned to have one queue per controller, but given the number of regular tasks we have this might not be required. It can be refactored in future to the single queue for all regular tasks._ 
```
// In worker add new processor named "myRegularTask" to existing setupSessionQueue function:
/**
 * Setup queue for session jobs.
 */
function setupSessionQueue() {
    createQueue('session').then(sessionQueue => {
        // Register processor
        sessionQueue.process('myRegularTask', job => myRegularTask (job.data));

        // Add myRegularTask periodic job, it gets triggered every 5 minutes. For add params spec see
        // https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd
        sessionQueue.add('myRegularTask', {}, {
            removeOnComplete: 2, // always keep N last jobs in Bull history, needed to pass result to callback on different node instance.
            removeOnFail: true,
            repeat: { every: ms('5m') },
        });
}
```
Snippets below are optional, they demonstrate how to run a callback on regular task completion (e.g. if you need to run something on different node instance when worker completes executing a regular task.
```
// If you need to run callback on regular job completion, in the app.js add callback to existing list:
    waitDb.then(() => {
        const listener = new JobCompletionListener('session');

        listener.addCallback('archiveExpiredSessions', session.cleanArchivedSessions);
        listener.addCallback('calcUserStats', session.regetUsersAfterStatsUpdate);
        
        // Add afterMyRegularTask callback for myRegularTask
        listener.addCallback('myRegularTask', afterMyRegularTask);
        
        listener.init();
    });
```
```
// In the applicable controller define a function that will be used as a callback:
export const afterMyRegularTask= function (data) {
    data = JSON.parse(data); // required as data comes serialised.
    console.log(data); // {c: 3} - this is what myRegularTask returned in data argument.
}
```

**Comment by kabalin** [comment]
### Logs output example
**User job (convertPhotosAll)**
userjob
**Regular task (archiveExpiredSession and session.cleanArchivedSessions callback)**
regtask

**Review by klimashkin — COMMENTED** [review]
I noticed `Promise.resolve({..})` is returned across multiple `async` functions.
Why do we need a promise wrapper?

**Comment by klimashkin** [comment]
Back in the days the biggest concern over moving many systemjs functions to the application was the memory usage.
Sucking the whole collections into nodejs memory didn't seem like a scalable way and supposed to blow one day.

But with the new Mongoose there is a simple solution. It supports async iterators now, so thing like 
```js
  const photos = await Photo.find(query, { _id: 0, cid: 1 }).sort({ cid: 1 }).exec();
  for (const photo of photos) {
    ...
  }
```
Can be rewritten to 
```js
  for await (photo stock of Photo.find(query, { _id: 0, cid: 1 }).sort({ cid: 1 })) {
    ..
  }
```
and it will use the cursor to pull documents asynchronously with streaming back pressure.

I think we should use it in methods like
`calcRegionStats`
`convertPhotosAll`
`clusterPhotosAll`
`calcUserStats`

**Comment by kabalin** [comment]
> I noticed `Promise.resolve({..})` is returned across multiple `async` functions.
> Why do we need a promise wrapper?

That is Bull convention for [ queue processor function](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess), either it should return promise or receive a second param which should be used as callback ([also info here](https://github.com/OptimalBits/bull#using-promises)). I decided to use promise, it is just a bit neater. Alternatively of course I can return an object from controller function but wrap it in promise within queue processor, let me know if that is more preferable.

>Back in the days the biggest concern over moving many systemjs functions to the application was the memory usage.
>Sucking the whole collections into nodejs memory didn't seem like a scalable way and supposed to blow one day.

Totally agree. Thanks for idea about cursor. I made changes. We should be aware of time limit for using cursor though, on potentially time consuming task (e.g. region stats) I expanded max run time. I think in other places we can keep it default (10 minutes) for now.

One thing I realised that won't work right now is using transactions, as it only possible to use them on [Mongo replica set](https://docs.mongodb.com/manual/replication/#transactions), not standalone server. There are places in code where we could benefit from them.

**Comment by klimashkin** [comment]
Thanks for the async cursor!

> That is Bull convention for queue processor function, either it should return promise or receive a second param which should be used as callback (also some info here). 

Sorry if I was not clear. Async function in JS already returns a promise itself, you can't return promise from an async function, it will be awaited again and its value will be returned, which is a wasted tick.

```js
var some = async () => Promise.resolve(1);
(async () => {
  console.log(await some()); // 1
})()
```
Wrapping return on a promise makes sense when it's a regular sync function, when it's async it's redundant because it's already a promise

**Comment by kabalin** [comment]
> Wrapping return in a promise makes sense when it's a regular sync function, when it's async then it's redundant because it's already a promise

Well spotted 👀, thanks! I removed excessive `Promise` and updated usage doc in the comments above.

**Review by klimashkin — APPROVED** [review]

**Pull request merged**
